version: "3.9"
services:
  nginx:
    container_name: nginx
    image: nginx:1.15.12-alpine
    restart: unless-stopped
    volumes:
      - ./deployments/demo:/etc/nginx/conf.d
    ports:
      - 80:80
      - 443:443
    networks:
      - mynetwork
    depends_on:
      - api

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
